;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append
        evil-backward-char
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-delete-line
        evil-digit-argument-or-evil-beginning-of-line
        evil-end-of-line
        evil-find-char
        evil-forward-char
        evil-insert
        evil-use-register
        ruby-electric-quote
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        evil-force-normal-state
        evil-goto-line
        evil-next-line
        evil-normal-state
        evil-previous-line
        linum-mode
        smex
        ))
