(global-set-key (kbd "RET") 'newline-and-indent)
(global-set-key (kbd "C-M-\\") 'indent-region-or-buffer)
(global-set-key (kbd "M-;") 'comment-dwim-line)
(global-set-key (kbd "M-/") 'smart-tab)
(global-set-key (kbd "M-x") 'helm-M-x)
