(diminish 'visual-line-mode)
(after-load 'abbrev (diminish 'abbrev-mode))
(after-load 'company (diminish 'company-mode))
(after-load 'emmet-mode (diminish 'emmet-mode))
(after-load 'eldoc (diminish 'eldoc-mode))
(after-load 'golden-ratio (diminish 'golden-ratio-mode))
(after-load 'hideshow (diminish 'hs-minor-mode))
(after-load 'magit (diminish 'magit-auto-revert-mode))
(after-load 'paredit (diminish 'paredit-mode))
(after-load 'projectile (diminish 'projectile-mode))
(after-load 'sackspace (diminish 'sackspace-mode))
(after-load 'undo-tree (diminish 'undo-tree-mode))
(after-load 'whitespace (diminish 'global-whitespace-mode))
(after-load 'yasnippet (diminish 'yas-minor-mode))
