(diminish 'visual-line-mode)
(eval-after-load "abbrev" '(diminish 'abbrev-mode))
(eval-after-load "eldoc" '(diminish 'eldoc-mode))
(eval-after-load "emmet" '(diminish 'emmet-mode))
(eval-after-load "golden-ratio" '(diminish 'golden-ratio-mode))
(eval-after-load "hideshow" '(diminish 'hs-minor-mode))
(eval-after-load "paredit" '(diminish 'paredit-mode))
(eval-after-load "projectile" '(diminish 'projectile-mode))
(eval-after-load "sackspace" '(diminish 'sackspace-mode))
(eval-after-load "ruby-electric" '(diminish 'ruby-electric-mode))
(eval-after-load "undo-tree" '(diminish 'undo-tree-mode))
(eval-after-load "whitespace" '(diminish 'global-whitespace-mode))
(eval-after-load "yasnippet" '(diminish 'yas-minor-mode))
